export const GET_TODOS = 'GET_TODOS'
export const ADD_TODOS = 'ADD_TODOS'
export const DELETE_TODOS = 'DELETE_TODOS'
export const UPDATE_TODOS = 'UPDATE_TODOS'

export const GET_USERS = 'GET_USERS'
export const POST_USERS = 'POST_USERS'
export const ADD_USERS = 'ADD_USERS'
export const DELETE_USERS = 'DELETE_USERS'
export const UPDATE_USERS = 'UPDATE_USERS'

export const GET_WEBTOONS = 'GET_WEBTOONS'
export const GET_EPISODES = 'GET_EPISODES'
export const GET_IMAGES = 'GET_IMAGES'

export const GET_MY_WEBTOONS = 'GET_MY_WEBTOONS'
export const ADD_MY_WEBTOONS = 'ADD_MY_WEBTOONS'
export const DELETE_MY_WEBTOONS = 'DELETE_MY_WEBTOONS'
export const UPDATE_MY_WEBTOONS = 'UPDATE_MY_WEBTOONS'

export const GET_MY_EPISODES = 'GET_MY_EPISODES'
export const ADD_MY_EPISODES = 'ADD_MY_EPISODES'
export const DELETE_MY_EPISODES = 'DELETE_MY_EPISODES'
export const UPDATE_MY_EPISODES = 'UPDATE_MY_EPISODES'

export const GET_MY_IMAGES = 'GET_MY_IMAGES'
export const ADD_MY_IMAGES = 'ADD_MY_IMAGES'
export const DELETE_MY_IMAGES = 'DELETE_MY_IMAGES'
export const UPDATE_MY_IMAGES = 'UPDATE_MY_IMAGES'

export const GET_FAVORITES = 'GET_FAVORITES'
export const ADD_FAVORITES = 'ADD_FAVORITES'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'

export const UPLOAD_PHOTO_MY_PROFIL ='UPLOAD_PHOTO_MY_PROFIL'
export const UPLOAD_PHOTO_MY_WEBTOONS ='UPLOAD_PHOTO_MY_WEBTOONS'
export const UPLOAD_PHOTO_MY_EPISODES ='UPLOAD_PHOTO_MY_EPISODES'
export const UPLOAD_PHOTO_MY_IMAGES ='UPLOAD_PHOTO_MY_IMAGES'
